{
 "title": "led switcher",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method,path,instance) (rate(http_duration_seconds_count{app=\"ledswitcher\",path!=\"/metrics\"}[5m]))",
     "legendFormat": "{{path}} - {{method}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (method) (ledswitcher_http_duration_seconds_sum{path=\"/led\"} / ledswitcher_http_duration_seconds_count{path=\"/led\"})",
     "legendFormat": "led - {{method}}"
    },
    {
     "expr": "avg(ledswitcher_http_duration_seconds_sum{path=\"/register\"} / ledswitcher_http_duration_seconds_count{path=\"/register\"})",
     "legendFormat": "register"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by (path,status_code) (rate(ledswitcher_http_duration_seconds_count{status_code!~\"2.*\"}[2m]))",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  }
 ]
}