{
 "title": "ledswitcher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "registered nodes",
   "type": "stat",
   "gridPos": { "h": 16, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (ledswitcher_registry_node_count)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "server - call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(ledswitcher_server_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "server - latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, method, code) (ledswitcher_server_api_request_duration_seconds_bucket))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "client - call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(ledswitcher_client_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "client - latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, method, code) (ledswitcher_client_api_request_duration_seconds_bucket))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  }
 ]
}
{
 "title": "ledswitcher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "registered nodes",
   "type": "stat",
   "gridPos": { "h": 16, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (ledswitcher_registry_node_count)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "server - call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(ledswitcher_server_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "server - latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, method, code) (ledswitcher_server_api_request_duration_seconds_bucket))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "client - call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(ledswitcher_client_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "client - latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, method, code) (ledswitcher_client_api_request_duration_seconds_bucket))",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  }
 ]
}