apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ledswitcher

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledswitcher
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledswitcher-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ledswitcher
subjects:
  - kind: ServiceAccount
    name: ledswitcher
---