name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.18
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.18
      target: ledswitcher
