name: Build

on:
  push:
    branches:
      - master
      - linux6
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      image: ghcr.io/clambin/ledswitcher
      dockerfile: build/Dockerfile
