name: Build

on:
  push:
    branches:
      - master
      - heap
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go122
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go122
    with:
      target: ledswitcher
