name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go122
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go122
    with:
      target: ledswitcher
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@go122
