name: Test

on:
  push:
    branches-ignore:
      - master
      - http
  pull_request_target:

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@maib
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
